# Generated by Django 4.2.10 on 2024-03-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thiet_bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('activate', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=100)),
                ('sub_folder_format', models.CharField(max_length=100)),
                ('send_time', models.IntegerField()),
                ('check_activation', models.CharField(max_length=100)),
                ('check_time', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('time_out', models.IntegerField()),
                ('round_decimal', models.IntegerField()),
                ('FTP_method', models.CharField(max_length=100)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiet_bi.thietbi')),
            ],
        ),
        migrations.CreateModel(
            name='FTPServerFileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.CharField(max_length=100)),
                ('province_code', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('station_code', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=100)),
                ('sensor_list', models.CharField(max_length=100)),
                ('FTP_server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTP_Server.ftpservers')),
            ],
        ),
    ]
