# Generated by Django 4.2.10 on 2024-03-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thiet_bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('bucker', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('store_time', models.BigIntegerField(default=2)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiet_bi.thietbi')),
            ],
        ),
    ]
