# Generated by Django 4.2.10 on 2024-03-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thiet_bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ID', models.CharField(max_length=100)),
                ('location_x', models.CharField(max_length=100)),
                ('location_y', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiet_bi.thietbi')),
            ],
        ),
    ]
